# Dockerfile.frontend
FROM nginx:alpine

# Remove a configuração padrão do Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copia os arquivos estáticos do frontend para o diretório do Nginx
COPY frontend/ /usr/share/nginx/html/

# Copia um arquivo de configuração customizado do Nginx
COPY nginx.conf /etc/nginx/conf.d/

# Expõe a porta padrão do Nginx
EXPOSE 80

# O Nginx já é o comando padrão de execução
CMD ["nginx", "-g", "daemon off;"]