# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./app/backend # BUILD É app/backend/
      dockerfile: Dockerfile.backend # O Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend:/app # O caminho local agora inclui 'app/'
      - ./data:/app/data
    environment:
      PYTHONUNBUFFERED: 1

  frontend:
    build:
      context: ./app/frontend # AGORA O CONTEXTO DE BUILD É app/frontend/
      dockerfile: Dockerfile.frontend # O Dockerfile.frontend está dentro do contexto
    ports:
      - "8001:80"
    volumes:
      - ./app/frontend:/usr/share/nginx/html # O caminho local agora inclui 'app/'
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - backend